project:
  type: website
  output-dir: docs

website:
  title: "Zhi Hong Website"
  #favicon: favicon.png
  navbar:
    #logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - dataVis.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



